import sys
import os
import json

# Add backend to path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from app.database.db import SessionLocal
from app.database.models import FraudAlerts
from app.ai.fraud_agent import FraudAgent

def execute_fraud_agent_investigation():
    session = SessionLocal()
    
    print("\n--- AUTONOMOUS AI SECURITY SYSTEM - LIVE INVESTIGATION ---")
    
    # Grab the latest fraud alert generated by test_fraud.py
    alert = session.query(FraudAlerts).order_by(FraudAlerts.id.desc()).first()
    
    if alert:
        print(f"[*] ALERT ID: {alert.id}")
        print(f"[*] RISK CATEGORY: {alert.risk_level}")
        print(f"[*] RAW SCORE: {alert.risk_score}")
        print(f"[*] ASSIGNED TRIGGER: {alert.trigger_event}")
        
        print("\n[AI AGENT ANALYZING FAISS BLOCKS AND LOG VECTORS...]")
        
        # This matches what Claude/Stitch will execute from the FastMCP wrapper
        report = FraudAgent.investigate_user_alert(alert.id)
        
        print("\n--- FINAL INVESTIGATION REPORT ---")
        print(json.dumps(report, indent=4))
    else:
        print("No recent fraud alerts were identified in the ecosystem.")
        
if __name__ == "__main__":
    execute_fraud_agent_investigation()
